#!/usr/bin/python
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'color_extract.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from std_msgs.msg import Int16
import sys

import rospy
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QDialog

class Ui_Form(object):

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(868, 858)
        rospy.init_node("UI")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setMaximum(255)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 0, 1, 1)
        self.verticalSlider = QtWidgets.QSlider(Form)
        self.verticalSlider.setMaximum(255)
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName("verticalSlider")
        self.gridLayout.addWidget(self.verticalSlider, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spinBox_2 = QtWidgets.QSpinBox(Form)
        self.spinBox_2.setMaximum(255)
        self.spinBox_2.setObjectName("spinBox_2")
        self.gridLayout_2.addWidget(self.spinBox_2, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(Form)
        self.verticalSlider_2.setMaximum(255)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.gridLayout_2.addWidget(self.verticalSlider_2, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_3 = QtWidgets.QSpinBox(Form)
        self.spinBox_3.setMaximum(255)
        self.spinBox_3.setObjectName("spinBox_3")
        self.gridLayout_3.addWidget(self.spinBox_3, 1, 0, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(Form)
        self.verticalSlider_3.setMaximum(255)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.gridLayout_3.addWidget(self.verticalSlider_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.spinBox_4 = QtWidgets.QSpinBox(Form)
        self.spinBox_4.setMaximum(255)
        self.spinBox_4.setObjectName("spinBox_4")
        self.gridLayout_4.addWidget(self.spinBox_4, 1, 0, 1, 1)
        self.verticalSlider_4 = QtWidgets.QSlider(Form)
        self.verticalSlider_4.setMaximum(255)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.gridLayout_4.addWidget(self.verticalSlider_4, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.spinBox_5 = QtWidgets.QSpinBox(Form)
        self.spinBox_5.setMaximum(255)
        self.spinBox_5.setObjectName("spinBox_5")
        self.gridLayout_5.addWidget(self.spinBox_5, 1, 0, 1, 1)
        self.verticalSlider_5 = QtWidgets.QSlider(Form)
        self.verticalSlider_5.setMaximum(255)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.gridLayout_5.addWidget(self.verticalSlider_5, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 0, 0, 1, 1)
        self.spinBox_6 = QtWidgets.QSpinBox(Form)
        self.spinBox_6.setMaximum(255)
        self.spinBox_6.setObjectName("spinBox_6")
        self.gridLayout_6.addWidget(self.spinBox_6, 1, 0, 1, 1)
        self.verticalSlider_6 = QtWidgets.QSlider(Form)
        self.verticalSlider_6.setMaximum(255)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.gridLayout_6.addWidget(self.verticalSlider_6, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_6)

        self.retranslateUi(Form)
        self.verticalSlider.valueChanged['int'].connect(self.spinBox.setValue)
        self.spinBox.valueChanged['int'].connect(self.verticalSlider.setValue)
        self.verticalSlider_2.valueChanged['int'].connect(self.spinBox_2.setValue)
        self.spinBox_2.valueChanged['int'].connect(self.verticalSlider_2.setValue)
        self.verticalSlider_3.valueChanged['int'].connect(self.spinBox_3.setValue)
        self.spinBox_3.valueChanged['int'].connect(self.verticalSlider_3.setValue)
        self.spinBox_4.valueChanged['int'].connect(self.verticalSlider_4.setValue)
        self.verticalSlider_4.valueChanged['int'].connect(self.spinBox_4.setValue)
        self.spinBox_5.valueChanged['int'].connect(self.verticalSlider_5.setValue)
        self.verticalSlider_5.valueChanged['int'].connect(self.spinBox_5.setValue)
        self.spinBox_6.valueChanged['int'].connect(self.verticalSlider_6.setValue)
        self.verticalSlider_6.valueChanged['int'].connect(self.spinBox_6.setValue)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "HMAX"))
        self.label_2.setText(_translate("Form", "HMIN"))
        self.label_3.setText(_translate("Form", "SMAX"))
        self.label_4.setText(_translate("Form", "SMIN"))
        self.label_5.setText(_translate("Form", "VMAX"))
        self.label_6.setText(_translate("Form", "VMIN"))
        self.verticalSlider.valueChanged['int'].connect(self.publish_one)
        self.verticalSlider_2.valueChanged['int'].connect(self.publish_two)
        self.verticalSlider_3.valueChanged['int'].connect(self.publish_three)
        self.verticalSlider_4.valueChanged['int'].connect(self.publish_four)
        self.verticalSlider_5.valueChanged['int'].connect(self.publish_five)
        self.verticalSlider_6.valueChanged['int'].connect(self.publish_six)
    def publish_one(self):
        self.pub_one=rospy.Publisher("Slider_one",Int16,queue_size=10)
        self.pub_one.publish(self.verticalSlider.value())
    def publish_two(self):
        self.pub_two=rospy.Publisher("Slider_two",Int16,queue_size=10)
        self.pub_two.publish(self.verticalSlider_2.value())
    def publish_three(self):
        self.pub_three=rospy.Publisher("Slider_three",Int16,queue_size=10)
        self.pub_three.publish(self.verticalSlider_3.value())
    def publish_four(self):
        self.pub_four=rospy.Publisher("Slider_four",Int16,queue_size=10)
        self.pub_four.publish(self.verticalSlider_4.value())
    def publish_five(self):
        self.pub_five=rospy.Publisher("Slider_five",Int16,queue_size=10)
        self.pub_five.publish(self.verticalSlider_5.value())
    def publish_six(self):
        self.pub_six=rospy.Publisher("Slider_six",Int16,queue_size=10)
        self.pub_six.publish(self.verticalSlider_6.value())
if __name__=="__main__":
    app = QApplication(sys.argv)
    form = QDialog()
    ui = Ui_Form()
    ui.setupUi(form)
    #print("Enter showUI!")
    form.show()
    app.exec_()